### ISSUE TITLE
External Packages

### ISSUE THREAD

**Issue by alanhdu** [blair-robot-project/Scoutmaster-9001#1]
So...I'm thinking that this project is some kind of practical joke (and if it is, I approve of the README), but in case it isn't:

You really shouldn't just put source code from external packages (i.e. beautiful soup and requests) in the project. That's what `pip` is for. Just `pip install bs4` and `pip install requests`, update `requirements.txt`, and you're good to go.

**Comment by theoduino** [comment]
I've fixed it. The problem is that too many people on this team don't seem to agree with PEP8. I have corrected this in commit 4772a09fce42267d12b5864d8e6cc60deb8b45f4

**Comment by alanhdu** [comment]
Huh...well, good look to you guys then. Although I should warn you about [things you should never do](http://www.joelonsoftware.com/articles/fog0000000069.html). Heed at your own discretion, of course.

I'd also recommend `sqlalchemy` instead of `dataset` (there's even `flask-sqlalchemy`!) You'll probably need a bunch of foreign keys, so a full-fledged ORM will probably work better than `dataset`.

**Comment by gentlecolts** [comment]
so like
i'm skimming that
and I see:
>It's important to remember that when you start from scratch there is *absolutely
no reason* to believe that you are going to do a better job than you did
the first time

this is like, just outright wrong
you've already gone through and done it once, you know what you did wrong
and you now have a better idea of how it should be
there are plenty of times when it's much easier to just rewrite things
properly than trying to fix a broken mess

**Comment by Marionumber1** [comment]
Joel is talking about this in the context of software companies. Obviously,
Microsoft rewriting their whole Windows product is a bad idea for business
(and they shouldn't, because NT is amazing as it is). But we have much more
freedom.
